#!/bin/bash

for file in $(find `dirname $0` -name "*.sh"); do
  abs=`readlink -f $file`
  if [ $(grep -c "^source $abs" $HOME/.bashrc) -eq 0 ]; then
    echo "source $abs" >> $HOME/.bashrc
  fi
done

source $HOME/.bashrc
